name: Testar runner Valheim

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on:
      - self-hosted
      - valheim

    steps:
      - name: Verificar Docker
        shell: pwsh
        run: |
          docker version
          docker compose version

      - name: Verificar projeto Valheim
        shell: pwsh
        working-directory: C:\Users\alessandro\OneDrive\projetos\valheim-server
        run: |
          docker compose config --quiet
          docker compose ps